### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by Sajidali123** [signifly/laravel-shopify#29]
How to work with pagination and display links on page using **paginateOrders()** or others functions.

**Comment by skellyk** [comment]
Did you ever figure this out? Looking into it now as well.

**Comment by Sajidali123** [comment]
No, i didn't find anything to display pagination links.

**Comment by zotopteam** [comment]
https://www.notion.so/Laravel-Shopify-424709fa6dd84defb0879ab8a1cb29fa#0074693880d04faf8309f6e6b9386da9

```php
$pages = $this->shopify->paginateProducts(['limit' => 100]); // returns Cursor

$results = collect();

foreach ($pages as $page) {
    // $page is a Collection of ApiResources
    $results = $results->merge($page);
}
```

**Comment by skellyk** [comment]
> https://www.notion.so/Laravel-Shopify-424709fa6dd84defb0879ab8a1cb29fa#0074693880d04faf8309f6e6b9386da9
> 
> ```
> $pages = $this->shopify->paginateProducts(['limit' => 100]); // returns Cursor
> 
> $results = collect();
> 
> foreach ($pages as $page) {
>     // $page is a Collection of ApiResources
>     $results = $results->merge($page);
> }
> ```

I had figured this out however the issue is it will always load every page. I couldn't figure out how to only load one page without getting all of them, and performance wise that's not great.

I ended up just storing records in a database and using eloquent's built in pagination.

**Comment by Razorsheep** [comment]
This is a good idea for an enhancement of the package. We will accept any PRs on this. 👍

**Comment by Razorsheep** [comment]
This is just the way pagination works in shopifys REST api. Currently there is no better way to implement pagination IMO than what you can see in this Cursor class:
https://github.com/signifly/laravel-shopify/blob/master/src/REST/Cursor.php
