### ISSUE TITLE
private apps deprecated -- support for custom apps?

### ISSUE THREAD

**Issue by ccennis** [signifly/laravel-shopify#33]
I am attempting to set up API connection to a custom shopify app. My connection string example from Shopify does  not match the base creds provided in the shopify docs to instantiate a Shopify instance. 

documented: 
`$shopify = new Shopify(
                env('SHOPIFY_API_KEY'),
                env('SHOPIFY_API_PASSWORD'),
                env('SHOPIFY_DOMAIN'),
                env('SHOPIFY_API_VERSION')
            );`

After creating my custom app, I do not have an api_password, I  have been given an access_token, an api_key and a secret_key.

example cURL from Shopify docs:

`curl -X GET \
https://url-test.myshopify.com/admin/products.json \
-H 'Content-Type: application/json' \
-H 'X-Shopify-Access-Token: XXXXX'`

Is this an incompatibility with new shopify setup or do I need to instantiate a new object another way?

**Comment by bureauvk** [comment]
You need to use the general API-key for `SHOPIFY_API_KEY` and once u set all permissions for the Admin API there will be another key that will only show once, use that for `SHOPIFY_PASSWORD`.

**Comment by cennis-ck** [comment]
> You need to use the general API-key for `SHOPIFY_API_KEY` and once u set all permissions for the Admin API there will be another key that will only show once, use that for `SHOPIFY_PASSWORD`.
![Screen Shot 2022-07-14 at 11 09 35 AM](https://user-images.githubusercontent.com/52422380/179015833-6a8eeaa3-a2b9-45be-8d40-26a70013273f.png)

No combination of these keys seems to authenticate. It is very frustrating.

**Comment by zsoltjanes** [comment]
Change your .env variable `SHOPIFY_API_PASSWORD` to `SHOPIFY_PASSWORD`.

![image](https://user-images.githubusercontent.com/7995436/181271500-56445683-2cb5-4e41-8a59-5c942376231f.png)

**Comment by VictorGarcia** [comment]
The same thing is happening to me. Modifying the env variable doesn't help. After looking into the library's code, I can see that it is using BasicAuth to authenticate. Probably Shopify has dropped this functionality? I've replaced this method with sending the `X-Shopify-Access-Token` header and it is authenticating properly and I'm able to query resources.

src/Shopify.php
```
public function getHttpClient(): PendingRequest
    {
        return $this->httpClient ??= Http::baseUrl($this->getBaseUrl())
            ->withHeaders(['X-Shopify-Access-Token' => $this->password]);
    }
```

**Comment by Israel5** [comment]
Thank you to everyone that interacted with this post.

In fact, there was a typo in the [documentation](https://www.notion.so/Laravel-Shopify-424709fa6dd84defb0879ab8a1cb29fa), which has now been fixed.

@ccennis, @cennis-ck and @leetimeleisure, are you guys still with problems?
In case you are, @zotopteam, @bureauvk and @zotopteam gave good insights on how to solve it.

### To summarize

#### Step 1
You need to go to `https://{your-shop}.myshopify.com/admin/settings/apps/development` and create your app.
<img width="959" alt="Screen Shot 2022-09-13 at 9 45 36 PM" src="https://user-images.githubusercontent.com/63180786/190040348-a7698377-7004-469e-b891-c1eac6ac20e9.png">

#### Step 2
Once you have created your app, click the option `Configure Admin API scopes`.
<img width="959" alt="Screen Shot 2022-09-13 at 9 49 18 PM" src="https://user-images.githubusercontent.com/63180786/190040724-25ad09da-4de7-4f2e-8b21-82642e3feedf.png">

On this next screen, you must select all scopes (roles) your API key needs access to and then hit the `Save` button.
<img width="959" alt="Screen Shot 2022-09-13 at 9 58 00 PM" src="https://user-images.githubusercontent.com/63180786/190041661-56347a61-7cff-4e94-bd5c-09c386a17009.png">

If you try to access an endpoint your API Key has no access to, the application will throw an error `403 Forbidden` and you will get an error similar to this:
```json
{
	"errors": "[API] This action requires merchant approval for read_products scope."
}
```

More information about Scopes can be found in the following links:
1. https://shopify.dev/apps/auth/basic-http
2. https://shopify.dev/api/usage/access-scopes

#### Step 3
To finish the process, you have to click the tab `API credentials` and then on the button `Install app`.
<img width="959" alt="Screen Shot 2022-09-13 at 10 10 38 PM" src="https://user-images.githubusercontent.com/63180786/190043078-5f120df5-27ce-4d76-8fa6-d29193cbff58.png">

On the popup, click the button `Install`.
<img width="959" alt="Screen Shot 2022-09-13 at 10 14 31 PM" src="https://user-images.githubusercontent.com/63180786/190043418-bdab9d9f-3bda-4e33-82af-3910ac7dfa2c.png">

Note that you will only be able to see your token once, so make sure you save it properly.
<img width="959" alt="Screen Shot 2022-09-13 at 10 16 49 PM" src="https://user-images.githubusercontent.com/63180786/190043757-d37b18ac-378e-46c2-9c43-919cfe16075f.png">

If everything is correct, your Admin API access token starts with `shpat_` and has a 32-character hash string in front of it.
<img width="566" alt="Screen Shot 2022-09-13 at 10 52 03 PM" src="https://user-images.githubusercontent.com/63180786/190048324-9f0870ea-6770-4d64-af53-8d8addb35cc2.png">
Don't forget to include this in the `SHOPIFY_PASSWORD` key in your `.env` file.

#### Step 4
Now you can instantiate the class once again in your code and it should work:
<img width="959" alt="image" src="https://user-images.githubusercontent.com/63180786/190046697-dce36368-9a52-467c-99c7-a950debc5cc1.png">
<img width="959" alt="Screen Shot 2022-09-13 at 10 44 27 PM" src="https://user-images.githubusercontent.com/63180786/190047548-620af523-4784-4fc9-a522-f4e1a771011a.png">

---

For now, we will close this issue, but please, feel free to reopen it in case of problems.
