### ISSUE TITLE
There is a warning on Laravel 9，ApiResource::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void

### ISSUE THREAD

**Issue by zotopteam** [signifly/laravel-shopify#34]
There is a warning on Laravel 9

laravel.WARNING: Return type of Signifly\Shopify\REST\Resources\ApiResource::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/release/project/picoding_dev/vendor/signifly/laravel-shopify/src/REST/Resources/ApiResource.php on line 110

**Comment by joecampo** [comment]
Hey @zotopteam, this isn't a L9 issue, but rather PHP8.1. 

I've opened a PR (#30) to address this. In the mean time, you can use my fork to suppress the deprecation notice. 

In your `composer.json`

```json
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/joecampo/laravel-shopify"
        }
```

and require the package w/ the fork:

```json
"signifly/laravel-shopify": "dev-8.1-support"
```

**Comment by joecampo** [comment]
Hey there @achowatt @antoniandre @michaelvalentin @Toreheimann

Apologies to ping you, but I've noticed the person who committed the most isn't apart of your org anymore.

Does Signifly plan to maintain this package going forward? If not, I have no problem maintaining a proper fork (or even help maintain this package directly if Signifly allows).

Thanks for your time!

**Comment by zotopteam** [comment]
@joecampo Thank you very much. By the way, I also want to know whether this package is still maintained.

**Comment by Razorsheep** [comment]
Thanks for the help @joecampo, we've accepted your pull requests! 👍

**Comment by joecampo** [comment]
@Razorsheep no problem! Would you be able to tag a new release? :)

**Comment by Razorsheep** [comment]
Sorry for the delay @joecampo tagged a new release now! 👍
