### ISSUE TITLE
SHOPIFY_API_PASSWORD to SHOPIFY_PASSWORD

### ISSUE THREAD

**Issue by zsoltjanes** [signifly/laravel-shopify#35]
Documentation says we have to setup the `SHOPIFY_API_PASSWORD` but its not exists only the `SHOPIFY_PASSWORD` exists.

**Comment by Razorsheep** [comment]
Thanks for the headsup - if shopify changed their naming we will update this.

**Comment by Razorsheep** [comment]
See #33

**Comment by Israel5** [comment]
Hi @zsoltjanes,

Thank you for your collaboration. The [documentation](https://www.notion.so/Laravel-Shopify-424709fa6dd84defb0879ab8a1cb29fa) was already updated.
Let us know if you have further questions.

Köszönöm.

**Comment by zsoltjanes** [comment]
You are welcome!
Szívesen! :)
