### ISSUE TITLE
setInventoryLevel Function

### ISSUE THREAD

**Issue by sohaib-wajid** [signifly/laravel-shopify#36]
Hello,

I'm getting The resource you are looking for could not be found. while updating stock on Shopify using this function Shopify->setInventoryLevel().

the log file is attached below.

[2022-10-06 10:13:36] local.ERROR: The resource you are looking for could not be found. {"exception":"[object] (Signifly\\Shopify\\Exceptions\\NotFoundException(code: 0): The resource you are looking for could not be found. at /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/signifly/laravel-shopify/src/Exceptions/Handler.php:24)
[stacktrace]
#0 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/signifly/laravel-shopify/src/Support/MakesHttpRequests.php(125): Signifly\\Shopify\\Exceptions\\Handler->handle()
#1 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/signifly/laravel-shopify/src/Support/MakesHttpRequests.php(32): Signifly\\Shopify\\Shopify->handleErrorResponse()
#2 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/signifly/laravel-shopify/src/REST/Actions/ManagesInventory.php(76): Signifly\\Shopify\\Shopify->post()
#3 /home/sohaib/htdocs/Projects/InProgress/ezbooks/app/Modules/Shopify.php(19): Signifly\\Shopify\\Shopify->setInventoryLevel()
#4 /home/sohaib/htdocs/Projects/InProgress/ezbooks/app/Modules/ApiStockUpdate.php(25): App\\Modules\\Shopify->ShopifyStocks()
#5 /home/sohaib/htdocs/Projects/InProgress/ezbooks/app/Http/Controllers/Api/ShopifyOrderApiController.php(107): App\\Modules\\ApiStockUpdate->update()
#6 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Api\\ShopifyOrderApiController->store()
#7 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#8 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#9 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\\Routing\\Route->runController()
#10 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Route->run()
#11 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#12 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#14 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(126): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(102): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest()
#16 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(54): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequestUsingNamedLimiter()
#17 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()
#18 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then()
#20 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack()
#21 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Routing\\Router->runRoute()
#22 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute()
#23 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch()
#24 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#25 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#27 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#28 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#30 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#31 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#33 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#35 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Fruitcake\\Cors\\HandleCors->handle()
#37 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#39 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then()
#41 /home/sohaib/htdocs/Projects/InProgress/ezbooks/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#42 /home/sohaib/htdocs/Projects/InProgress/ezbooks/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()

**Comment by kalimraza** [comment]
This is correct message returned from Shopify.

I think you are giving invalid "inventoryItemId"  in function

**Comment by Razorsheep** [comment]
Yes, it seems like you might be trying to access a resource that doesn't exist. Closing this issue.
