### ISSUE TITLE
deprecated Fulfillment API endpoints

### ISSUE THREAD

**Issue by prabalinfo** [signifly/laravel-shopify#44]
"TL;DR: Please note that your custom app(s) are leveraging deprecated Fulfillment API endpoints. "

Getting error from Shopify support. In our APP we using the Shopify API Version = 2023-01. Let me know we need to change any settings / configuration ?

**Comment by Spotnyk** [comment]
@prabalinfo You likely have some changes you'll need make to your workflow.

See: https://shopify.dev/docs/apps/fulfillment/migrate

**Comment by Razorsheep** [comment]
As @Spotnyk mentions Shopify has migrated to use the FulfillmentOrder api endpoints to handle most fulfillment logic. the package is prepared to make the new calls.
