### ISSUE TITLE
The given data failed to pass validation.

### ISSUE THREAD

**Issue by Ravensborn** [signifly/laravel-shopify#7]
Post requests to shopify using this package causes the folllowing error.

**The given data failed to pass validation.**

![image](https://user-images.githubusercontent.com/27031143/134487887-176462aa-a34b-4d6f-b151-8860b2c43de3.png)

Even when using shopify api documentation examples, the error is still there. but get requests work fine like getting the products from shopify.

Example Code:

```
        $shopify = new Shopify(
            config('env.SHOPIFY_API_KEY'),
            config('env.SHOPIFY_API_PASSWORD'),
            config('env.SHOPIFY_DOMAIN'),
            config('env.SHOPIFY_API_VERSION')
        );
        
            $customer = [
                'customer' => [
                    'first_name' => $user->first_name,
                    'last_name' => $user->last_name,
                    'email' => $user->email,
                    'phone' => $user->phone,
                    'verified_email' => true,
                    'addresses' => [
                        [
                            'first_name' => $user->first_name,
                            'last_name' => $user->last_name,
                            'phone' => $user->phone,
                            'country' => $address->country,
                            'province' => $address->region,
                            'city' => $address->city,
                            'address1' => $address->address,
                            'zip' => $address->postal_code,
                        ]
                    ]
                ]
            ];


          $shopify->createCustomer($customer);
```

**Comment by pactode** [comment]
From your example code you only need to pass in the data, not the `customer` key. The package takes care of wrapping the data with the customer key.

**Comment by Ravensborn** [comment]
> From your example code you only need to pass in the data, not the `customer` key. The package takes care of wrapping the data with the customer key.
> 
> ```
>           $customer = [
>                     'first_name' => $user->first_name,
>                     'last_name' => $user->last_name,
>                     'email' => $user->email,
>                     'phone' => $user->phone,
>                     'verified_email' => true,
>                     'addresses' => [
>                         [
>                             'first_name' => $user->first_name,
>                             'last_name' => $user->last_name,
>                             'phone' => $user->phone,
>                             'country' => $address->country,
>                             'province' => $address->region,
>                             'city' => $address->city,
>                             'address1' => $address->address,
>                             'zip' => $address->postal_code,
>                         ]
>                     ]
>             ];
> 
> 
>           $shopify->createCustomer($customer);
> ```

I tried without customer key as well, same issue.

**Comment by pactode** [comment]
Did you check the validation errors from Shopify?

You can do that by wrapping your call in a try-catch block.

```php
use Signifly\Shopify\Exceptions\ValidationException;

try {
    // your request
} catch (ValidationException $e) {
    dump($e->errors); // log errors or something

    throw $e;
}
```

FYI: If you use the v1.1.2 release you can enable including validation errors in the exception message via the config.
